### ISSUE TITLE
[CHORE] Project-Setting

### ISSUE THREAD

**Issue by dev-madilyn** [team-MUMENT/MUMENT-iOS#1]
## 🎧 이슈 요약

* 프로젝트 세팅을 진행합니다.

## 🎶 Branch Name

- chore/#1-project-setting

## 🎹 체크 리스트

- [x]  폰트
- [x]  컬러
- [x]  앱 이름
- [x]  Base
- [x]  Extension
- [x]  진입 뷰 설정(SceneDelegate)
- [x]  컬러셋, 이미지셋 분리
- [x]  라이브러리 설치 - Snapkit, Then, Alamofire, RxSwift
- [x] Tabbar

**Comment by lhb8106** [comment]
정빈 화이팅 ! 머싯다 !

**Comment by dev-madilyn** [comment]
@lhb8106 혜빈아 고맙다 !
