### ISSUE TITLE
[FEAT] 보관함 탭 상단 탭 구현

### ISSUE THREAD

**Issue by daminoworld** [team-MUMENT/MUMENT-iOS#35]
## 🎧 About

* 보관함 탭 상단의 두 가지 탭 구현 

## 🎶 Branch Name

* feat/#35-Storage-TopTab

## 🎹 To do

- [ ] 상단 네비 바 우선 세팅
- [ ] 뷰페이저 이용해서 구현

**Comment by dev-madilyn** [comment]
다미노 영광의 첫 이슈! 파이탱!
